### ISSUE TITLE
Error on long data dump

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/app#101]
`v2.0.0-beta1`

```
[previous exception] [object] (PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payload' at row 1 at /app/vendor/cycle/database/src/Driver/Driver.php:443)
```

I think it possible to use blob cell for very long data.

**Comment by Semdevmaster** [comment]
Подтверждаю, проблема актуальна! Версия v2.0.0-beta2
В стабильной версии всё норм, огромные объекты выводятся в лог нормально.

**Comment by butschster** [comment]
@roxblnfk @Semdevmaster Thank you for the issue!
