### ISSUE TITLE
Do you consider deploying the front-end page separately?

### ISSUE THREAD

**Issue by AuroraYolo** [buggregator/app#24]

**Comment by butschster** [comment]
Hi @codingheping. What do you mean?

**Comment by codingheping** [comment]
I want to use swow instead of swoole, https://github.com/swow/swow

**Comment by butschster** [comment]
It's not possible to separate app into a backend and frontend parts. And there is no support for swow. Frontend only works with  supports the buggregator app and it's a part of buggregator.
