### ISSUE TITLE
is it possible to password protect the dashboard

### ISSUE THREAD

**Issue by danielzzz** [buggregator/app#57]
hi, 

is it possible to somehow password protect the dashboard?

this would be useful for tracking live servers.
I know I could tunnel it to my local installation, but with more developers it get's a bit complicated.

thanks, cheers, dan

**Comment by butschster** [comment]
Hi @danielzzz! 
I'm going to add password protection in v2.1 release, maybe earlier. I need some time to finish my current activities and I will start working on authorization and also on separating events by domains (Possibility to send logs on a separate domains connected with buggregator instance and then filtering by domain)

**Comment by danielzzz** [comment]
ok, thank you!
