### ISSUE TITLE
mail server seems to cache emails and is not refreshing

### ISSUE THREAD

**Issue by danielzzz** [buggregator/app#62]
hi, I have found some strange behavior. 

I am using buggregator as a smtp server, but it keeps showing the same email message over and over.

not sure if it caches it somehow or is not refreshing or something...

cheers, dan

**Comment by butschster** [comment]
Hi @danielzzz!
Could you try a new release v1.18.3?

**Comment by danielzzz** [comment]
hi Pavel, I pulled the latest version from docker and it seems to be working correctly now.
thanks a lot!
dan
