### ISSUE TITLE
Get the UI which is shown on the homepage

### ISSUE THREAD

**Issue by dstollie** [buggregator/app#76]
When I pull the latest version of buggregator from docker hub I get the app version which is shown in the images in the Readme but when I saw the version on the website I fell in love with that UI. I did not find a way in the readme to be able to get that version I might miss something but is there a way to get this fancy looking version?

![Screenshot 2022-03-22 at 22 15 02](https://user-images.githubusercontent.com/7110155/159577223-8c020815-9fa1-4c01-ad9b-a4dedfac8ed4.png)

By the way; I love working with buggregator it really makes me more productive if there is a way I can fund you some coffee please let me know!

**Comment by butschster** [comment]
<img width="453" src="https://user-images.githubusercontent.com/773481/159636709-606c7be9-3ab1-41d2-987c-de56bbe6e998.png">

**Comment by dstollie** [comment]
@butschster thanks for the response but I do not see the sidebar at all, I think im using the wrong port

**Comment by butschster** [comment]
Hi @dstollie 

Oh, I finally understood :)

It's a new experimental version of buggregator

Try this command 
```
docker run --pull always -p 23517:8000 -p 1025:1025 -p 9912:9912 -p 9913:9913 butschster/buggregator:v2.0.0-beta
```

**Comment by dstollie** [comment]
Whoop whoop, thanks, this is awesome!
