### ISSUE TITLE
how to start without docker?

### ISSUE THREAD

**Issue by anditsung** [buggregator/app#77]
i have this error when opening the page

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '/Volumes/MacData/work/buggregator/server.php' (include_path='.:/usr/local/Cellar/php/8.0.12/share/php/pear') in Unknown on line 0

**Comment by butschster** [comment]
hello! 

`./rr serve`

**Comment by anditsung** [comment]
Got it working. But the port use is 8000.
I have to set ray port to 8000 to make it work

**Comment by butschster** [comment]
> Got it working. But the port use is 8000. I have to set ray port to 8000 to make it work

You can change port in the config file [.rr.yaml](https://github.com/buggregator/app/blob/master/.rr.yaml#L13)

**Comment by anditsung** [comment]
> > Got it working. But the port use is 8000. I have to set ray port to 8000 to make it work
> 
> 
> 
> You can change port in the config file [.rr.yaml](https://github.com/buggregator/app/blob/master/.rr.yaml#L13)

Do i change the port for web or add server for ray with port 23517?

**Comment by butschster** [comment]
> > > Got it working. But the port use is 8000. I have to set ray port to 8000 to make it work
> > 
> > 
> > You can change port in the config file [.rr.yaml](https://github.com/buggregator/app/blob/master/.rr.yaml#L13)
> 
> Do i change the port for web or add server for ray with port 23517?

You can change default port for ray via config file `ray.php` in your app https://spatie.be/docs/ray/v1/configuration/framework-agnostic-php

**Comment by anditsung** [comment]
Thank you for fast response. I think need to add this to documentation for easy use
