### ISSUE TITLE
No events receiving

### ISSUE THREAD

**Issue by robov** [buggregator/app#78]
Any ideas?
I powered up the docker containers as you specified
I installed vardumper and ray in my laravel application
in the controller I do
dd('hello'); ray('hiya');
But when I navigate to http://localhost:23517/
It keeps spinning "Hurry! Give me something. I can't wait to show it."
So I guess no events are coming in

Any ideas

**Comment by butschster** [comment]
Hi @robov 
Did you configure env variables?
- for var dumper https://github.com/buggregator/app#settings
- for ray https://github.com/buggregator/app#laravel-settings-2

**Comment by robov** [comment]
Yes. I did the following
i used
    buggregator:
        image: butschster/buggregator:latest
        ports:
        - 23517:8000
        - 1025:1025
        - 9912:9912
        - 9913:9913

to startup the server

then I installed inside the laravel container
composer require --dev symfony/var-dumper

then I added to my laravel app
VAR_DUMPER_FORMAT=server
VAR_DUMPER_SERVER=127.0.0.1:9912        

The in a controller
dd('ii');

http://127.0.0.1:23517/
shows the "give me something" screen

---
When I add
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1025

and send an email, then I get:
Connection could not be established with host "127.0.0.1:1025": stream_socket_client(): Unable to connect to 127.0.0.1:1025 (Connection refused)

**Comment by robov** [comment]
I have received an email. I had to make the following changes. Based on your question I realized they were both in a different network. So I had to add the network, and specify the host

MAIL_MAILER=smtp
MAIL_HOST=buggregator
MAIL_PORT=1025

  buggregator:
    image: butschster/buggregator:latest
    ports:
      - 23517:8000
      - 1025:1025
      - 9912:9912
      - 9913:9913
    networks:
      - my-docker-network-name

**Comment by robov** [comment]
and for plain dumper:
VAR_DUMPER_SERVER=buggregator:9912

**Comment by robov** [comment]
Any ideas for sentry:
SENTRY_LARAVEL_DSN=http://sentry@buggregator:23517/1
SENTRY_LARAVEL_DSN=http://sentry@127.0.0.1:23517/1
php artisan sentry:test
results in 
Failed to connect to 127.0.0.1 port 23517: Connection refused for "http://127.0.0.1:23517/api/1/store/"."

**Comment by butschster** [comment]
use 8000 port insted of 23517 inside docker!

**Comment by robov** [comment]
Awesome, I did not realize the 8000 port was generic
